[package]
name = "flate"
version = "0.1.0"
authors = ["Pat Gavlin <pgavlin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.20"

[[bin]]
name = "flate"
path = "main.rs"
